/** Member fields returned by the stack sharing API. */
export interface SharingMember {
  email?: string
  groups?: number[]
  instance?: string
  name?: string
  only_in_groups?: boolean
  public_name?: string
  read_only?: boolean
  status: string
}

/** Group fields returned by the stack sharing API. */
export interface SharingGroup {
  addedBy: number
  color?: string
  id?: string
  name: string
  read_only: boolean
  revoked?: boolean
}

/** Member enriched by cozy-sharing for display. */
export type SharingMemberRecipient = SharingMember & {
  avatarPath: string
  /** Stable display identifier generated by cozy-sharing. */
  index: string
  /** Position in the members array returned by the stack. */
  memberIndex: number
  sharingId: string
  type: 'one-way' | 'two-way'
}

/** Group enriched by cozy-sharing for display. */
export type SharingGroupRecipient = SharingGroup & {
  /** Position in the groups array returned by the stack. */
  groupIndex: number
  /** Stable display identifier generated by cozy-sharing. */
  index: string
  members: SharingMemberRecipient[]
  owner: SharingMemberRecipient
  sharingId: string
}

/** Member or group returned by cozy-sharing recipient selectors. */
export type SharingRecipient = SharingMemberRecipient | SharingGroupRecipient
